/* Generated By:JavaCC: Do not edit this line. ProofJavaParserConstants.java */
package de.uka.ilkd.key.parser.proofjava;

public interface ProofJavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int ASSERT = 14;
  int AT = 15;
  int BIGINT = 16;
  int REAL = 17;
  int BOOLEAN = 18;
  int BREAK = 19;
  int BYTE = 20;
  int CASE = 21;
  int CATCH = 22;
  int CHAR = 23;
  int CLASS = 24;
  int CONST = 25;
  int CONTINUE = 26;
  int _DEFAULT = 27;
  int DO = 28;
  int DOUBLE = 29;
  int ELSE = 30;
  int ENUM = 31;
  int EXTENDS = 32;
  int FALSE = 33;
  int FINAL = 34;
  int FINALLY = 35;
  int FLOAT = 36;
  int FOR = 37;
  int FREE = 38;
  int GOTO = 39;
  int IF = 40;
  int IMPLEMENTS = 41;
  int IMPORT = 42;
  int INSTANCEOF = 43;
  int INT = 44;
  int INTERFACE = 45;
  int LOCSET = 46;
  int LONG = 47;
  int MAP = 48;
  int METHODFRAME = 49;
  int NATIVE = 50;
  int NEW = 51;
  int NULL = 52;
  int PACKAGE = 53;
  int PRIVATE = 54;
  int PROTECTED = 55;
  int PUBLIC = 56;
  int RETURN = 57;
  int SEQ = 58;
  int SET = 59;
  int SHORT = 60;
  int STATIC = 61;
  int SUPER = 62;
  int SWITCH = 63;
  int SYNCHRONIZED = 64;
  int THIS = 65;
  int THROW = 66;
  int THROWS = 67;
  int TRANSACTIONBEGIN = 68;
  int TRANSACTIONCOMMIT = 69;
  int TRANSACTIONFINISH = 70;
  int TRANSACTIONABORT = 71;
  int TRANSIENT = 72;
  int TRUE = 73;
  int TRY = 74;
  int VOID = 75;
  int VOLATILE = 76;
  int WHILE = 77;
  int VARARGDENOTER = 78;
  int STRICTFP = 79;
  int INTEGER_LITERAL = 80;
  int DECIMAL_LITERAL = 81;
  int HEX_LITERAL = 82;
  int OCTAL_LITERAL = 83;
  int FLOATING_POINT_LITERAL = 84;
  int EXPONENT = 85;
  int CHARACTER_LITERAL = 86;
  int STRING_LITERAL = 87;
  int IDENTIFIER = 88;
  int LETTER = 89;
  int DIGIT = 90;
  int DL_EMBEDDED_FUNCTION = 91;
  int MAP_FUNCTION = 92;
  int LPAREN = 93;
  int RPAREN = 94;
  int LBRACE = 95;
  int RBRACE = 96;
  int LBRACKET = 97;
  int RBRACKET = 98;
  int SEMICOLON = 99;
  int COMMA = 100;
  int DOT = 101;
  int ASSIGN = 102;
  int BANG = 103;
  int TILDE = 104;
  int HOOK = 105;
  int COLON = 106;
  int DOUBLECOLON = 107;
  int EQ = 108;
  int LE = 109;
  int GE = 110;
  int NE = 111;
  int SC_OR = 112;
  int SC_AND = 113;
  int INCR = 114;
  int DECR = 115;
  int PLUS = 116;
  int MINUS = 117;
  int STAR = 118;
  int SLASH = 119;
  int BIT_AND = 120;
  int BIT_OR = 121;
  int XOR = 122;
  int REM = 123;
  int LSHIFT = 124;
  int PLUSASSIGN = 125;
  int MINUSASSIGN = 126;
  int STARASSIGN = 127;
  int SLASHASSIGN = 128;
  int ANDASSIGN = 129;
  int ORASSIGN = 130;
  int XORASSIGN = 131;
  int REMASSIGN = 132;
  int LSHIFTASSIGN = 133;
  int RSIGNEDSHIFTASSIGN = 134;
  int RUNSIGNEDSHIFTASSIGN = 135;
  int SHARP = 136;
  int RUNSIGNEDSHIFT = 137;
  int RSIGNEDSHIFT = 138;
  int GT = 139;
  int IMPLICITIDENTIFIER = 140;
  int LT = 141;
  int UNICODE_BYTE_ORDER_MARKER = 142;
  int UNKNOWN_CHARACTER_SEQUENCE = 143;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"@\"",
    "\"\\\\bigint\"",
    "\"\\\\real\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"\\\\free\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"\\\\locset\"",
    "\"long\"",
    "\"\\\\map\"",
    "\"method-frame\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"\\\\seq\"",
    "\"\\\\set\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"#beginJavaCardTransaction\"",
    "\"#commitJavaCardTransaction\"",
    "\"#finishJavaCardTransaction\"",
    "\"#abortJavaCardTransaction\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"...\"",
    "\"strictfp\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DL_EMBEDDED_FUNCTION>",
    "<MAP_FUNCTION>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"::\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"#\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "<IMPLICITIDENTIFIER>",
    "\"<\"",
    "\"\\ufeff\"",
    "<UNKNOWN_CHARACTER_SEQUENCE>",
    "\"\\\\indexOf\"",
    "\"\\\\seq_length\"",
    "\"\\\\seq_get\"",
    "\"@(\"",
    "\"\\\\singleton\"",
    "\"\\\\set_union\"",
    "\"\\\\intersect\"",
    "\"\\\\set_minus\"",
    "\"\\\\all_fields\"",
    "\"\\\\all_objects\"",
    "\"\\\\seq_singleton\"",
    "\"\\\\seq_concat\"",
    "\"\\\\seq_sub\"",
    "\"\\\\seq_reverse\"",
    "\"\\\\seq_put\"",
    "\"..\"",
    "\"\\\\empty\"",
    "\"\\\\seq_empty\"",
    "\"\\\\map_empty\"",
    "\"#catchAll\"",
    "\"result->\"",
    "\"source=\"",
    "\",this=\"",
  };

}
